---
  - name: "Exercise for setting up a web server in an EC 2"
    hosts: all
    user: ubuntu
    vars:
      - ansible_python_interpreter: /usr/bin/python3
      - ansible_host_key_checking: false
      - ansible_stdout_callback: yaml

    roles:
      - setup